global:
  scrape_interval: 15s  # Интервал сбора метрик

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: loki
    static_configs:
      - targets: ['loki:3100']

  - job_name: spring_boot_app
    metrics_path: /actuator/prometheus  # Указываем путь к метрикам Spring Boot
    scheme: https  # Использование HTTPS
    tls_config:
      insecure_skip_verify: true  # Отключить проверку сертификата (для тестирования)
    static_configs:
      - targets: ['192.168.75.8:8003']  # Изменено на HTTPS адрес приложения
      
  - job_name: postgres
    static_configs:
      - targets: ['postgres-exporter:9187']



